#!/usr/bin/env bash
./motor_spi.py -2
./motor_spi.py -2
sleep 2
./motor_spi.py 0
./motor_spi.py 0
sleep 1
./motor_spi.py 2
./motor_spi.py 2
sleep 4
./motor_spi.py 0
./motor_spi.py 0
sleep 1
./motor_spi.py -2
./motor_spi.py -2
sleep 3
./motor_spi.py 0
./motor_spi.py 0
